"use client";
import { useState, useCallback, useRef, useEffect } from "react";
import { useRouter } from "next/navigation";
import { MODELS, ModelInfo, WPSite, Config, UserData, defaultCfg, ARTICLE_SIZES, FREE_MAX_WORDS } from "@/lib/constants";
import { generateArticle, generateTitlesAPI, type ArticleResult } from "@/lib/api";
import { Sec, Inp, RunBtn } from "@/components/ui";
import SettingsForm from "@/components/SettingsForm";
import OutlineEditor from "@/components/OutlineEditor";
import ResultPanel from "@/components/ResultPanel";
import WritingLoader from "@/components/WritingLoader";
import UpgradePopup from "@/components/UpgradePopup";
import ImageTemplateGallery from "@/components/images/ImageTemplateGallery";
import { createClient } from "@/lib/supabase/client";
import { getWPSites, saveWPSites } from "@/lib/wp-sites";

function StepHeading({ number, title, helper }: { number: string; title: string; helper: string }) {
  return <div className="flex gap-3"><span className="grid h-7 w-7 flex-none place-items-center rounded-full bg-amber-100 text-xs font-bold text-amber-800">{number}</span><div><h2 className="text-sm font-semibold text-slate-900">{title}</h2><p className="mt-0.5 text-xs leading-relaxed text-slate-500">{helper}</p></div></div>;
}

function EditorialEmptyState() {
  return <div className="mx-auto flex w-full max-w-2xl flex-1 flex-col justify-center py-8"><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-[0_16px_50px_rgba(53,45,32,.06)]"><div className="border-b border-stone-100 px-6 py-5 sm:px-8"><p className="text-xs font-semibold tracking-[.12em] text-amber-700">RUANG TULIS</p><h2 className="mt-2 font-bold text-2xl tracking-tight text-slate-900" style={{ fontFamily: "Sora,sans-serif" }}>Mulai dari ide Anda</h2><p className="mt-2 max-w-md text-sm leading-relaxed text-slate-600">Isi brief di sebelah kiri. Kami akan membantu menyusunnya menjadi draft yang siap Anda tinjau dan terbitkan.</p></div><div className="grid gap-6 px-6 py-6 sm:grid-cols-[1fr_190px] sm:px-8"><ol className="space-y-4">{[["1","Tentukan topik","Masukkan keyword atau masalah yang ingin dibahas."],["2","Pilih bentuk artikel","Atur panjang dan arahan singkat agar hasil terasa tepat."],["3","Tinjau draft Anda","Edit, cek SEO, lalu kirim ke WordPress saat sudah siap."]].map(([n, heading, body]) => <li key={n} className="flex gap-3"><span className="grid h-6 w-6 flex-none place-items-center rounded-full border border-amber-200 bg-amber-50 text-[11px] font-bold text-amber-800">{n}</span><div><p className="text-sm font-semibold text-slate-800">{heading}</p><p className="text-xs leading-relaxed text-slate-500">{body}</p></div></li>)}</ol><div className="relative min-h-[160px] rounded-xl border border-stone-200 bg-[#f8f4eb] p-4"><div className="absolute right-4 top-4 h-2 w-12 rounded bg-amber-200" /><div className="mt-6 rounded-md border border-stone-200 bg-white p-3 shadow-sm"><div className="h-2 w-20 rounded bg-slate-700" /><div className="mt-3 h-1.5 w-full rounded bg-stone-200" /><div className="mt-2 h-1.5 w-4/5 rounded bg-stone-200" /><div className="mt-5 border-l-2 border-amber-400 pl-2"><div className="h-1.5 w-3/4 rounded bg-stone-200" /><div className="mt-2 h-1.5 w-full rounded bg-stone-200" /></div></div><p className="absolute bottom-3 text-[11px] font-medium text-slate-500">Contoh: draft artikel siap dibaca</p></div></div></div></div>;
}

export default function GeneratePage() {
  const router = useRouter(); const [user, setUser] = useState<UserData | null>(null); const [authUser, setAuthUser] = useState<any>(null); const [wpSites, setWpSites] = useState<WPSite[]>([]);
  const isAdmin = user?.role === "admin"; const hasTrialArticle = (user?.trial_articles_remaining ?? 0) > 0; const isPro = isAdmin || hasTrialArticle || (user?.plan ?? "free") !== "free"; const credits = user?.credits ?? 0;
  const wordQuota = user?.monthly_word_quota ?? null; const wordsUsed = user?.monthly_words_used ?? 0; const wordsRemaining = wordQuota === null ? null : Math.max(0, wordQuota - wordsUsed); const maxWordsPerArticle = user?.max_words_per_article ?? 0;
  const maxWordsInSize = (size: string) => Math.max(...[...size.matchAll(/\d[\d.]*/g)].map(match => Number(match[0].replace(/\./g, ""))), 0);
  const availableSizes = wordQuota !== null ? ARTICLE_SIZES.filter(size => maxWordsInSize(size) <= maxWordsPerArticle) : isPro ? ARTICLE_SIZES : ARTICLE_SIZES.slice(0, 3);
  const [cfg, setCfg] = useState<Config>(defaultCfg()); const [model, setModel] = useState<ModelInfo>(MODELS[0]); const [keyword, setKeyword] = useState(""); const [title, setTitle] = useState(""); const [outlineRows, setOutlineRows] = useState<{ type: string; text: string }[]>([]); const [wpSel, setWpSel] = useState<WPSite | null>(null);
  const [loading, setLoading] = useState(false); const [genTitleLoading, setGenTitleLoading] = useState(false); const [titleSuggestions, setTitleSuggestions] = useState<string[]>([]); const [result, setResult] = useState<ArticleResult | null>(null); const [error, setError] = useState<string | null>(null); const [showUpgrade, setShowUpgrade] = useState(false); const [upgradeReason, setUpgradeReason] = useState(""); const [mobileTab, setMobileTab] = useState<"form" | "result">("form");
  const resultRef = useRef<HTMLDivElement>(null); const draftSaveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const fetchUser = useCallback(async (uid: string) => { const res = await fetch(`/api/user?userId=${uid}`); if (res.ok) setUser(await res.json()); }, []);
  useEffect(() => { setWpSites(getWPSites()); const sb = createClient(); sb.auth.getUser().then(({ data: { user } }) => { if (!user) { router.push("/login"); return; } setAuthUser(user); fetchUser(user.id); }); }, [fetchUser, router]);
  const addWp = useCallback((s: WPSite) => setWpSites(prev => { const next = [...prev, s]; saveWPSites(next); return next; }), []); const removeWp = useCallback((id: number) => setWpSites(prev => { const next = prev.filter(x => x.id !== id); saveWPSites(next); return next; }), []);
  const selectedWords = maxWordsInSize(!isPro ? FREE_MAX_WORDS : cfg.articleSize); const hasGenerationAccess = isAdmin || hasTrialArticle || (wordsRemaining !== null ? selectedWords <= maxWordsPerArticle && wordsRemaining >= selectedWords : credits >= 7);
  const handleGenerateTitle = async () => { if (!keyword.trim()) return; setGenTitleLoading(true); setTitleSuggestions(await generateTitlesAPI(keyword)); setGenTitleLoading(false); };
  const generate = async () => { if (!keyword.trim()) return; if (!hasGenerationAccess) { setUpgradeReason("Anda memerlukan 1 hak artikel atau paket aktif untuk membuat artikel."); setShowUpgrade(true); return; } setLoading(true); setResult(null); setError(null); setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }), 100); try { const outline = outlineRows.map(r => `${r.type}: ${r.text}`).join("\n"); const article = await generateArticle({ ...cfg, keyword, title, outline }); setResult(article); setMobileTab("result"); if (authUser) fetchUser(authUser.id); } catch (e: any) { if (e.message?.includes("Kredit")) { setUpgradeReason(e.message); setShowUpgrade(true); } else { setError(e.message); setMobileTab("result"); } } setLoading(false); };
  const saveDraftPatch = useCallback((patch: Record<string, unknown>) => { if (!result?.id) return; if (draftSaveTimer.current) clearTimeout(draftSaveTimer.current); draftSaveTimer.current = setTimeout(() => { fetch(`/api/articles/${result.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }).catch(() => undefined); }, 800); }, [result?.id]);
  useEffect(() => () => { if (draftSaveTimer.current) clearTimeout(draftSaveTimer.current); }, []);
  return <div className="editorial-workspace h-full flex flex-col bg-[#f8f7f3]">
    <header className="flex flex-shrink-0 items-center gap-3 border-b border-stone-200 bg-[#fffefa] py-5 pl-16 pr-5 lg:px-8"><div className="grid h-9 w-9 place-items-center rounded-lg bg-amber-100 text-amber-800">✦</div><div><h1 className="text-base font-bold text-slate-900" style={{ fontFamily: "Sora,sans-serif" }}>Ruang Tulis</h1><p className="text-xs text-slate-500">Dari ide sederhana menjadi artikel yang siap dibaca</p></div>{user && <span className={`ml-auto rounded-full border px-3 py-1.5 text-xs font-semibold ${hasGenerationAccess ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-amber-200 bg-amber-50 text-amber-800"}`}>{hasGenerationAccess ? (wordsRemaining === null ? "Siap membuat artikel" : `${wordsRemaining.toLocaleString("id-ID")} kata tersisa`) : "Kuota belum mencukupi"}</span>}</header>
    <div className="lg:hidden fixed bottom-0 left-0 right-0 z-40 flex border-t border-stone-200 bg-[#fffefa]"><button onClick={() => setMobileTab("form")} className={`flex-1 py-3 text-xs font-semibold ${mobileTab === "form" ? "text-amber-800" : "text-slate-500"}`}>✦ Isi brief</button><button onClick={() => setMobileTab("result")} className={`flex-1 py-3 text-xs font-semibold ${mobileTab === "result" ? "text-amber-800" : "text-slate-500"}`}>▤ Hasil artikel</button></div>
    <div className="flex min-h-0 flex-1 gap-6 overflow-hidden px-3 py-4 pb-20 sm:px-5 lg:px-8 lg:py-7 lg:pb-7">{showUpgrade && <UpgradePopup onClose={() => setShowUpgrade(false)} reason={upgradeReason} />}
      <div className={`${mobileTab === "form" ? "flex" : "hidden"} lg:flex w-full lg:w-[390px] flex-shrink-0 flex-col gap-4 overflow-y-auto pb-8 pr-1.5`}>
        <section className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><StepHeading number="1" title="Topik artikel" helper="Mulai dengan satu kata kunci atau pertanyaan pelanggan Anda." /><div className="mt-5 space-y-4"><Inp label="Keyword utama" val={keyword} set={setKeyword} placeholder="Contoh: cara memulai bisnis online" maxLen={500} /><div><div className="mb-1.5 flex items-center justify-between"><label className="text-sm font-semibold text-slate-800">Judul artikel <span className="font-normal text-slate-400">(opsional)</span></label><button onClick={handleGenerateTitle} disabled={!keyword.trim() || genTitleLoading} className="text-xs font-semibold text-amber-700 hover:text-amber-900 disabled:opacity-40">{genTitleLoading ? "Mencari ide..." : "Bantu cari judul"}</button></div><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Kosongkan untuk membuat judul otomatis" className="h-11 w-full rounded-lg border border-stone-300 bg-white px-3 text-sm text-slate-800 outline-none placeholder:text-stone-400 focus:border-amber-500 focus:ring-2 focus:ring-amber-100" />{titleSuggestions.length > 0 && <div className="mt-2 rounded-lg border border-amber-100 bg-amber-50/50 p-2">{titleSuggestions.map((t, i) => <button key={i} onClick={() => { setTitle(t); setTitleSuggestions([]); }} className="block w-full rounded px-2 py-1.5 text-left text-xs text-slate-700 hover:bg-white">{t}</button>)}</div>}</div></div></section>
        <section className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><StepHeading number="2" title="Bentuk artikel" helper="Pilih panjang dan tambahkan konteks yang perlu ada di dalam draft." /><div className="mt-5 space-y-4"><div className="flex flex-col gap-1.5"><label className="text-sm font-semibold text-slate-800">Panjang artikel</label><select value={!isPro ? FREE_MAX_WORDS : cfg.articleSize} onChange={e => setCfg(prev => ({ ...prev, articleSize: e.target.value }))} className="h-11 rounded-lg border border-stone-300 bg-white px-3 text-sm text-slate-800 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100">{availableSizes.map(size => <option key={size} value={size}>{size}</option>)}</select></div><Inp label="Arahan untuk artikel" val={cfg.details} set={value => setCfg(prev => ({ ...prev, details: value }))} placeholder="Poin penting, data, sudut bahasan, atau hal yang perlu dihindari..." multiline rows={4} maxLen={6000} note="Opsional, tetapi membantu hasil draft lebih sesuai kebutuhan Anda." /></div></section>
        <section className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm"><StepHeading number="3" title="Pilihan tambahan" helper="Sesuaikan struktur dan pengaturan bila diperlukan. Semua pilihan ini opsional." /><div className="mt-4 space-y-2"><Sec title="Struktur artikel" icon="§" defaultOpen={false}><OutlineEditor rows={outlineRows} setRows={setOutlineRows} /></Sec><SettingsForm cfg={cfg} set={setCfg} model={model} setModel={setModel} wpSites={wpSites} addWp={addWp} removeWp={removeWp} wpSel={wpSel} setWpSel={setWpSel} mode="single" credits={credits} isPro={isPro} isAio={false} isAdmin={isAdmin} /></div></section>
        <div className="sticky bottom-0 border-t border-stone-100 bg-[#f8f7f3]/95 pt-4 backdrop-blur"><RunBtn onClick={generate} loading={loading} disabled={!keyword.trim() || !hasGenerationAccess} label={hasTrialArticle ? "Gunakan 1 artikel" : "Buat artikel"} sublabel="Sedang menyusun draft..." /><p className="mt-2 text-center text-xs text-slate-500">{hasGenerationAccess ? (wordsRemaining === null ? "Draft akan siap untuk ditinjau dalam beberapa saat." : `Menggunakan hingga ${selectedWords.toLocaleString("id-ID")} kata dari kuota Anda.`) : "Aktifkan paket atau tambah kuota untuk melanjutkan."}</p>{!isAdmin && !hasGenerationAccess && <button onClick={() => setShowUpgrade(true)} className="mt-2 w-full text-xs font-semibold text-amber-800 hover:underline">Lihat pilihan paket</button>}</div>
      </div>
      <div className={`${mobileTab === "result" ? "flex" : "hidden"} lg:flex flex-1 flex-col overflow-hidden min-w-0`} ref={resultRef}>{!result && !loading && !error && (keyword.trim() ? <div className="flex-1 overflow-y-auto rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><ImageTemplateGallery title={title.trim() || keyword.trim()} keyword={keyword.trim()} brand="" /><p className="mt-3 text-center text-xs text-slate-500">Anda dapat memilih desain featured image lagi setelah artikel selesai dibuat.</p></div> : <EditorialEmptyState />)}{loading && <WritingLoader />}{error && <div className="m-auto max-w-md rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-800">Tidak dapat membuat draft: {error}</div>}{result && <ResultPanel content={result.contentMarkdown} articleTitle={result.title} metaDescription={result.meta.description} keyword={keyword} slug={result.slug} model={model} wpSites={wpSel ? [wpSel] : wpSites} synds={cfg.synds} userId={user?.id} onContentChange={html => saveDraftPatch({ content_html: html })} onFeaturedImageChange={image => saveDraftPatch({ featured_preset: image })} />}</div>
    </div></div>;
}
